//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseProject.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedResources_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResources_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CourseProject.Resources.SharedResources.en", typeof(SharedResources_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign as Admin.
        /// </summary>
        internal static string AdminActionAssignAdmin {
            get {
                return ResourceManager.GetString("AdminActionAssignAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block.
        /// </summary>
        internal static string AdminActionBlock {
            get {
                return ResourceManager.GetString("AdminActionBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string AdminActionDelete {
            get {
                return ResourceManager.GetString("AdminActionDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Admin Role.
        /// </summary>
        internal static string AdminActionRemoveAdmin {
            get {
                return ResourceManager.GetString("AdminActionRemoveAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string AdminActions {
            get {
                return ResourceManager.GetString("AdminActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unblock.
        /// </summary>
        internal static string AdminActionUnblock {
            get {
                return ResourceManager.GetString("AdminActionUnblock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one user..
        /// </summary>
        internal static string AdminErrorNoUsersSelected {
            get {
                return ResourceManager.GetString("AdminErrorNoUsersSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User management.
        /// </summary>
        internal static string AdminPanelTitle {
            get {
                return ResourceManager.GetString("AdminPanelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        internal static string AdminRoleAdmin {
            get {
                return ResourceManager.GetString("AdminRoleAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string AdminRoleUser {
            get {
                return ResourceManager.GetString("AdminRoleUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string AdminStatusActive {
            get {
                return ResourceManager.GetString("AdminStatusActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocked.
        /// </summary>
        internal static string AdminStatusBlocked {
            get {
                return ResourceManager.GetString("AdminStatusBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string AdminTableEmail {
            get {
                return ResourceManager.GetString("AdminTableEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string AdminTableName {
            get {
                return ResourceManager.GetString("AdminTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        internal static string AdminTableRole {
            get {
                return ResourceManager.GetString("AdminTableRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string AdminTableStatus {
            get {
                return ResourceManager.GetString("AdminTableStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        internal static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course project.
        /// </summary>
        internal static string CP {
            get {
                return ResourceManager.GetString("CP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Template.
        /// </summary>
        internal static string CreateTemplate {
            get {
                return ResourceManager.GetString("CreateTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current image.
        /// </summary>
        internal static string CurrentImage {
            get {
                return ResourceManager.GetString("CurrentImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description cannot exceed 500 characters..
        /// </summary>
        internal static string DescriptionTooLong {
            get {
                return ResourceManager.GetString("DescriptionTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Template.
        /// </summary>
        internal static string EditTemplate {
            get {
                return ResourceManager.GetString("EditTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education.
        /// </summary>
        internal static string Education {
            get {
                return ResourceManager.GetString("Education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid action or no users selected..
        /// </summary>
        internal static string ErrorInvalidAction {
            get {
                return ResourceManager.GetString("ErrorInvalidAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input..
        /// </summary>
        internal static string ErrorInvalidInput {
            get {
                return ResourceManager.GetString("ErrorInvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed..
        /// </summary>
        internal static string ErrorLogin {
            get {
                return ResourceManager.GetString("ErrorLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration failed..
        /// </summary>
        internal static string ErrorRegister {
            get {
                return ResourceManager.GetString("ErrorRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        internal static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        internal static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image URL cannot exceed 500 characters..
        /// </summary>
        internal static string ImageUrlTooLong {
            get {
                return ResourceManager.GetString("ImageUrlTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string LanguageEnglish {
            get {
                return ResourceManager.GetString("LanguageEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string LanguageSelector {
            get {
                return ResourceManager.GetString("LanguageSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        internal static string LanguageSpanish {
            get {
                return ResourceManager.GetString("LanguageSpanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string LoginEmail {
            get {
                return ResourceManager.GetString("LoginEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string LoginPassword {
            get {
                return ResourceManager.GetString("LoginPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        internal static string LoginRememberMe {
            get {
                return ResourceManager.GetString("LoginRememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required..
        /// </summary>
        internal static string NameRequired {
            get {
                return ResourceManager.GetString("NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name cannot exceed 100 characters..
        /// </summary>
        internal static string NameTooLong {
            get {
                return ResourceManager.GetString("NameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Panel.
        /// </summary>
        internal static string NavAdminPanel {
            get {
                return ResourceManager.GetString("NavAdminPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string NavHome {
            get {
                return ResourceManager.GetString("NavHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string NavLogin {
            get {
                return ResourceManager.GetString("NavLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string NavLogout {
            get {
                return ResourceManager.GetString("NavLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string NavRegister {
            get {
                return ResourceManager.GetString("NavRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file chosen.
        /// </summary>
        internal static string NoFileChosen {
            get {
                return ResourceManager.GetString("NoFileChosen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No templates found.
        /// </summary>
        internal static string NoResults {
            get {
                return ResourceManager.GetString("NoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public.
        /// </summary>
        internal static string Public {
            get {
                return ResourceManager.GetString("Public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish.
        /// </summary>
        internal static string Publish {
            get {
                return ResourceManager.GetString("Publish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quiz.
        /// </summary>
        internal static string Quiz {
            get {
                return ResourceManager.GetString("Quiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string RegisterButton {
            get {
                return ResourceManager.GetString("RegisterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string RegisterEmail {
            get {
                return ResourceManager.GetString("RegisterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string RegisterName {
            get {
                return ResourceManager.GetString("RegisterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string RegisterPassword {
            get {
                return ResourceManager.GetString("RegisterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string RegisterTitle {
            get {
                return ResourceManager.GetString("RegisterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Results.
        /// </summary>
        internal static string SearchResults {
            get {
                return ResourceManager.GetString("SearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} action applied successfully..
        /// </summary>
        internal static string SuccessActionApplied {
            get {
                return ResourceManager.GetString("SuccessActionApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected templates deleted successfully..
        /// </summary>
        internal static string SuccessDeleteTemplate {
            get {
                return ResourceManager.GetString("SuccessDeleteTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged in successfully..
        /// </summary>
        internal static string SuccessLogin {
            get {
                return ResourceManager.GetString("SuccessLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged out successfully..
        /// </summary>
        internal static string SuccessLogout {
            get {
                return ResourceManager.GetString("SuccessLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected templates published successfully..
        /// </summary>
        internal static string SuccessPublishTemplate {
            get {
                return ResourceManager.GetString("SuccessPublishTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered successfully..
        /// </summary>
        internal static string SuccessRegister {
            get {
                return ResourceManager.GetString("SuccessRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template created successfully..
        /// </summary>
        internal static string SuccessTemplateCreated {
            get {
                return ResourceManager.GetString("SuccessTemplateCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template deleted successfully..
        /// </summary>
        internal static string SuccessTemplateDeleted {
            get {
                return ResourceManager.GetString("SuccessTemplateDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template updated successfully..
        /// </summary>
        internal static string SuccessTemplateUpdated {
            get {
                return ResourceManager.GetString("SuccessTemplateUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected templates unpublished successfully..
        /// </summary>
        internal static string SuccessUnpublishTemplate {
            get {
                return ResourceManager.GetString("SuccessUnpublishTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        internal static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g., quiz, education.
        /// </summary>
        internal static string TagsPlaceholder {
            get {
                return ResourceManager.GetString("TagsPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags cannot exceed 500 characters..
        /// </summary>
        internal static string TagsTooLong {
            get {
                return ResourceManager.GetString("TagsTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template not found or access denied..
        /// </summary>
        internal static string TemplateNotFoundOrAccessDenied {
            get {
                return ResourceManager.GetString("TemplateNotFoundOrAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Templates.
        /// </summary>
        internal static string TemplatesTitle {
            get {
                return ResourceManager.GetString("TemplatesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please correct the input errors..
        /// </summary>
        internal static string TErrorInvalidInput {
            get {
                return ResourceManager.GetString("TErrorInvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        internal static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme cannot exceed 50 characters..
        /// </summary>
        internal static string ThemeTooLong {
            get {
                return ResourceManager.GetString("ThemeTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpublish.
        /// </summary>
        internal static string Unpublish {
            get {
                return ResourceManager.GetString("Unpublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID is required..
        /// </summary>
        internal static string UserIdRequired {
            get {
                return ResourceManager.GetString("UserIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View template.
        /// </summary>
        internal static string ViewTemplate {
            get {
                return ResourceManager.GetString("ViewTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
