//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseProject.Resources {
    using System;
    using System.Reflection;
    using System.Resources;
    using System.Globalization;
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResources {
        private static ResourceManager resourceMan;
        private static CultureInfo resourceCulture;
        
        public SharedResources() {}
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    resourceMan = new ResourceManager("CourseProject.Resources.SharedResources", typeof(SharedResources).GetTypeInfo().Assembly);
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

public static string NavHome => ResourceManager.GetString("NavHome", resourceCulture);
public static string NavLogout => ResourceManager.GetString("NavLogout", resourceCulture);
public static string NavLogin => ResourceManager.GetString("NavLogin", resourceCulture);
public static string NavRegister => ResourceManager.GetString("NavRegister", resourceCulture);
public static string NavAdminPanel => ResourceManager.GetString("NavAdminPanel", resourceCulture);
public static string LanguageSelector => ResourceManager.GetString("LanguageSelector", resourceCulture);
public static string LanguageEnglish => ResourceManager.GetString("LanguageEnglish", resourceCulture);
public static string LanguageSpanish => ResourceManager.GetString("LanguageSpanish", resourceCulture);
public static string SuccessActionApplied => ResourceManager.GetString("SuccessActionApplied", resourceCulture);
public static string ErrorInvalidAction => ResourceManager.GetString("ErrorInvalidAction", resourceCulture);
public static string SuccessLogin => ResourceManager.GetString("SuccessLogin", resourceCulture);
public static string ErrorLogin => ResourceManager.GetString("ErrorLogin", resourceCulture);
public static string SuccessRegister => ResourceManager.GetString("SuccessRegister", resourceCulture);
public static string ErrorRegister => ResourceManager.GetString("ErrorRegister", resourceCulture);
public static string SuccessLogout => ResourceManager.GetString("SuccessLogout", resourceCulture);
public static string ErrorInvalidInput => ResourceManager.GetString("ErrorInvalidInput", resourceCulture);
public static string AdminPanelTitle => ResourceManager.GetString("AdminPanelTitle", resourceCulture);
public static string AdminTableName => ResourceManager.GetString("AdminTableName", resourceCulture);
public static string AdminTableEmail => ResourceManager.GetString("AdminTableEmail", resourceCulture);
public static string AdminTableStatus => ResourceManager.GetString("AdminTableStatus", resourceCulture);
public static string AdminTableRole => ResourceManager.GetString("AdminTableRole", resourceCulture);
public static string AdminStatusBlocked => ResourceManager.GetString("AdminStatusBlocked", resourceCulture);
public static string AdminStatusActive => ResourceManager.GetString("AdminStatusActive", resourceCulture);
public static string AdminRoleAdmin => ResourceManager.GetString("AdminRoleAdmin", resourceCulture);
public static string AdminRoleUser => ResourceManager.GetString("AdminRoleUser", resourceCulture);
public static string AdminActions => ResourceManager.GetString("AdminActions", resourceCulture);
public static string AdminActionBlock => ResourceManager.GetString("AdminActionBlock", resourceCulture);
public static string AdminActionUnblock => ResourceManager.GetString("AdminActionUnblock", resourceCulture);
public static string AdminActionAssignAdmin => ResourceManager.GetString("AdminActionAssignAdmin", resourceCulture);
public static string AdminActionRemoveAdmin => ResourceManager.GetString("AdminActionRemoveAdmin", resourceCulture);
public static string AdminActionDelete => ResourceManager.GetString("AdminActionDelete", resourceCulture);
public static string LoginTitle => ResourceManager.GetString("LoginTitle", resourceCulture);
public static string LoginEmail => ResourceManager.GetString("LoginEmail", resourceCulture);
public static string LoginPassword => ResourceManager.GetString("LoginPassword", resourceCulture);
public static string LoginRememberMe => ResourceManager.GetString("LoginRememberMe", resourceCulture);
public static string LoginButton => ResourceManager.GetString("LoginButton", resourceCulture);
public static string RegisterTitle => ResourceManager.GetString("RegisterTitle", resourceCulture);
public static string RegisterEmail => ResourceManager.GetString("RegisterEmail", resourceCulture);
public static string RegisterPassword => ResourceManager.GetString("RegisterPassword", resourceCulture);
public static string RegisterName => ResourceManager.GetString("RegisterName", resourceCulture);
public static string RegisterButton => ResourceManager.GetString("RegisterButton", resourceCulture);
public static string AdminErrorNoUsersSelected => ResourceManager.GetString("AdminErrorNoUsersSelected", resourceCulture);
public static string CP => ResourceManager.GetString("CP", resourceCulture);
public static string Hello => ResourceManager.GetString("Hello", resourceCulture);
public static string TemplatesTitle => ResourceManager.GetString("TemplatesTitle", resourceCulture);
public static string CreateTemplate => ResourceManager.GetString("CreateTemplate", resourceCulture);
public static string EditTemplate => ResourceManager.GetString("EditTemplate", resourceCulture);
public static string Name => ResourceManager.GetString("Name", resourceCulture);
public static string Description => ResourceManager.GetString("Description", resourceCulture);
public static string Theme => ResourceManager.GetString("Theme", resourceCulture);
public static string Public => ResourceManager.GetString("Public", resourceCulture);
public static string Tags => ResourceManager.GetString("Tags", resourceCulture);
public static string TagsPlaceholder => ResourceManager.GetString("TagsPlaceholder", resourceCulture);
public static string Image => ResourceManager.GetString("Image", resourceCulture);
public static string Create => ResourceManager.GetString("Create", resourceCulture);
public static string Save => ResourceManager.GetString("Save", resourceCulture);
public static string Edit => ResourceManager.GetString("Edit", resourceCulture);
public static string Delete => ResourceManager.GetString("Delete", resourceCulture);
public static string Actions => ResourceManager.GetString("Actions", resourceCulture);
public static string Yes => ResourceManager.GetString("Yes", resourceCulture);
public static string No => ResourceManager.GetString("No", resourceCulture);
public static string Education => ResourceManager.GetString("Education", resourceCulture);
public static string Quiz => ResourceManager.GetString("Quiz", resourceCulture);
public static string Other => ResourceManager.GetString("Other", resourceCulture);
public static string SuccessTemplateCreated => ResourceManager.GetString("SuccessTemplateCreated", resourceCulture);
public static string SuccessTemplateUpdated => ResourceManager.GetString("SuccessTemplateUpdated", resourceCulture);
public static string SuccessTemplateDeleted => ResourceManager.GetString("SuccessTemplateDeleted", resourceCulture);
public static string TErrorInvalidInput => ResourceManager.GetString("TErrorInvalidInput", resourceCulture);
public static string UserIdRequired => ResourceManager.GetString("UserIdRequired", resourceCulture);
public static string TemplateNotFoundOrAccessDenied => ResourceManager.GetString("TemplateNotFoundOrAccessDenied", resourceCulture);
public static string NameRequired => ResourceManager.GetString("NameRequired", resourceCulture);
public static string TypeRequired => ResourceManager.GetString("TypeRequired", resourceCulture);
public static string NameTooLong => ResourceManager.GetString("NameTooLong", resourceCulture);
public static string DescriptionTooLong => ResourceManager.GetString("DescriptionTooLong", resourceCulture);
public static string ThemeTooLong => ResourceManager.GetString("ThemeTooLong", resourceCulture);
public static string TagsTooLong => ResourceManager.GetString("TagsTooLong", resourceCulture);
public static string ImageUrlTooLong => ResourceManager.GetString("ImageUrlTooLong", resourceCulture);
public static string Browse => ResourceManager.GetString("Browse", resourceCulture);
public static string NoFileChosen => ResourceManager.GetString("NoFileChosen", resourceCulture);
public static string CurrentImage => ResourceManager.GetString("CurrentImage", resourceCulture);
public static string SuccessDeleteTemplate => ResourceManager.GetString("SuccessDeleteTemplate", resourceCulture);
public static string SuccessPublishTemplate => ResourceManager.GetString("SuccessPublishTemplate", resourceCulture);
public static string SuccessUnpublishTemplate => ResourceManager.GetString("SuccessUnpublishTemplate", resourceCulture);
public static string Publish => ResourceManager.GetString("Publish", resourceCulture);
public static string Unpublish => ResourceManager.GetString("Unpublish", resourceCulture);
public static string View => ResourceManager.GetString("View", resourceCulture);
public static string Confirm => ResourceManager.GetString("Confirm", resourceCulture);
public static string ViewTemplate => ResourceManager.GetString("ViewTemplate", resourceCulture);
public static string Back => ResourceManager.GetString("Back", resourceCulture);
public static string Search => ResourceManager.GetString("Search", resourceCulture);
public static string SearchResults => ResourceManager.GetString("SearchResults", resourceCulture);
public static string NoResults => ResourceManager.GetString("NoResults", resourceCulture);
public static string SuccessQuestionAdded => ResourceManager.GetString("SuccessQuestionAdded", resourceCulture);
public static string QuestionNotFoundOrAccessDenied => ResourceManager.GetString("QuestionNotFoundOrAccessDenied", resourceCulture);
public static string ErrorUpdatingQuestionOrder => ResourceManager.GetString("ErrorUpdatingQuestionOrder", resourceCulture);
public static string String => ResourceManager.GetString("String", resourceCulture);
public static string Text => ResourceManager.GetString("Text", resourceCulture);
public static string Integer => ResourceManager.GetString("Integer", resourceCulture);
public static string Checkbox => ResourceManager.GetString("Checkbox", resourceCulture);
public static string AddQuestion => ResourceManager.GetString("AddQuestion", resourceCulture);
public static string Questions => ResourceManager.GetString("Questions", resourceCulture);
public static string ErrorDeletingQuestion => ResourceManager.GetString("ErrorDeletingQuestion", resourceCulture);
public static string EditQuestionPlaceholder => ResourceManager.GetString("EditQuestionPlaceholder", resourceCulture);
public static string ConfirmDeleteQuestion => ResourceManager.GetString("ConfirmDeleteQuestion", resourceCulture);
public static string Title => ResourceManager.GetString("Title", resourceCulture);
public static string Type => ResourceManager.GetString("Type", resourceCulture);
public static string SelectType => ResourceManager.GetString("SelectType", resourceCulture);
public static string Add => ResourceManager.GetString("Add", resourceCulture);
public static string ErrorNoTemplatesSelected => ResourceManager.GetString("ErrorNoTemplatesSelected", resourceCulture);
public static string MaxQuestionsPerType => ResourceManager.GetString("MaxQuestionsPerType", resourceCulture);
public static string QuestionsList => ResourceManager.GetString("QuestionsList", resourceCulture);
public static string VisibleInResults => ResourceManager.GetString("VisibleInResults", resourceCulture);
public static string HiddenInResults => ResourceManager.GetString("HiddenInResults", resourceCulture);
public static string SuccessQuestionUpdated => ResourceManager.GetString("SuccessQuestionUpdated", resourceCulture);
public static string SuccessQuestionDeleted => ResourceManager.GetString("SuccessQuestionDeleted", resourceCulture);
public static string SuccessOrderUpdated => ResourceManager.GetString("SuccessOrderUpdated", resourceCulture);
public static string EditQuestion => ResourceManager.GetString("EditQuestion", resourceCulture);
public static string AllTemplates => ResourceManager.GetString("AllTemplates", resourceCulture);
public static string PublicOnly => ResourceManager.GetString("PublicOnly", resourceCulture);
public static string PrivateOnly => ResourceManager.GetString("PrivateOnly", resourceCulture);
public static string Settings => ResourceManager.GetString("Settings", resourceCulture);
public static string Close => ResourceManager.GetString("Close", resourceCulture);
public static string Loading => ResourceManager.GetString("Loading", resourceCulture);
public static string SuccessFormSubmitted => ResourceManager.GetString("SuccessFormSubmitted", resourceCulture);
public static string FillForm => ResourceManager.GetString("FillForm", resourceCulture);
public static string Submit => ResourceManager.GetString("Submit", resourceCulture);
public static string Cancel => ResourceManager.GetString("Cancel", resourceCulture);
public static string ViewForm => ResourceManager.GetString("ViewForm", resourceCulture);
public static string CreatedAt => ResourceManager.GetString("CreatedAt", resourceCulture);
public static string User => ResourceManager.GetString("User", resourceCulture);
public static string Answers => ResourceManager.GetString("Answers", resourceCulture);
public static string Forms => ResourceManager.GetString("Forms", resourceCulture);
public static string LightTheme => ResourceManager.GetString("LightTheme", resourceCulture);
public static string DarkTheme => ResourceManager.GetString("DarkTheme", resourceCulture);
public static string Dashboard => ResourceManager.GetString("Dashboard", resourceCulture);
public static string FormsTitle => ResourceManager.GetString("FormsTitle", resourceCulture);
public static string Template => ResourceManager.GetString("Template", resourceCulture);
public static string AggregatedResults => ResourceManager.GetString("AggregatedResults", resourceCulture);
public static string NoAggregatedData => ResourceManager.GetString("NoAggregatedData", resourceCulture);
public static string Question => ResourceManager.GetString("Question", resourceCulture);
public static string Min => ResourceManager.GetString("Min", resourceCulture);
public static string Max => ResourceManager.GetString("Max", resourceCulture);
public static string Average => ResourceManager.GetString("Average", resourceCulture);
public static string MostCommonAnswer => ResourceManager.GetString("MostCommonAnswer", resourceCulture);
public static string TrueCount => ResourceManager.GetString("TrueCount", resourceCulture);
public static string FalseCount => ResourceManager.GetString("FalseCount", resourceCulture);
public static string ResultsList => ResourceManager.GetString("ResultsList", resourceCulture);
public static string FormId => ResourceManager.GetString("FormId", resourceCulture);
public static string SubmittedAt => ResourceManager.GetString("SubmittedAt", resourceCulture);
public static string InvalidQuestionIds => ResourceManager.GetString("InvalidQuestionIds", resourceCulture);
public static string DatabaseError => ResourceManager.GetString("DatabaseError", resourceCulture);
public static string ErrorFormsNotFound => ResourceManager.GetString("ErrorFormsNotFound", resourceCulture);
public static string ErrorNoPermission => ResourceManager.GetString("ErrorNoPermission", resourceCulture);
public static string ErrorNoFormsSelected => ResourceManager.GetString("ErrorNoFormsSelected", resourceCulture);
public static string ErrorNoValidForms => ResourceManager.GetString("ErrorNoValidForms", resourceCulture);
public static string SuccessDeleteForms => ResourceManager.GetString("SuccessDeleteForms", resourceCulture);
public static string AdminErrorNoFormsSelected => ResourceManager.GetString("AdminErrorNoFormsSelected", resourceCulture);
public static string EditForm => ResourceManager.GetString("EditForm", resourceCulture);
public static string SuccessFormUpdated => ResourceManager.GetString("SuccessFormUpdated", resourceCulture);
public static string Manage => ResourceManager.GetString("Manage", resourceCulture);
public static string Comments => ResourceManager.GetString("Comments", resourceCulture);
public static string NoComments => ResourceManager.GetString("NoComments", resourceCulture);
public static string AddComment => ResourceManager.GetString("AddComment", resourceCulture);
public static string CommentRequired => ResourceManager.GetString("CommentRequired", resourceCulture);
public static string SuccessCommentAdded => ResourceManager.GetString("SuccessCommentAdded", resourceCulture);
public static string CommentTooLong => ResourceManager.GetString("CommentTooLong", resourceCulture);
public static string DeleteComment => ResourceManager.GetString("DeleteComment", resourceCulture);
public static string CommentDeleted => ResourceManager.GetString("CommentDeleted", resourceCulture);
public static string CommentNotFound => ResourceManager.GetString("CommentNotFound", resourceCulture);
public static string Unauthorized => ResourceManager.GetString("Unauthorized", resourceCulture);
public static string Like => ResourceManager.GetString("Like", resourceCulture);
public static string Unlike => ResourceManager.GetString("Unlike", resourceCulture);
public static string LikeSuccess => ResourceManager.GetString("LikeSuccess", resourceCulture);
public static string UnlikeSuccess => ResourceManager.GetString("UnlikeSuccess", resourceCulture);
public static string MinimumInputMessage => ResourceManager.GetString("MinimumInputMessage", resourceCulture);
public static string RequiredField => ResourceManager.GetString("RequiredField", resourceCulture);
public static string TitleTooLong => ResourceManager.GetString("TitleTooLong", resourceCulture);
public static string LatestTemplates => ResourceManager.GetString("LatestTemplates", resourceCulture);
public static string Author => ResourceManager.GetString("Author", resourceCulture);
public static string TopTemplates => ResourceManager.GetString("TopTemplates", resourceCulture);
public static string FormsCount => ResourceManager.GetString("FormsCount", resourceCulture);
public static string NoDescription => ResourceManager.GetString("NoDescription", resourceCulture);
public static string AccessDenied => ResourceManager.GetString("AccessDenied", resourceCulture);
public static string NoAggregatorFound => ResourceManager.GetString("NoAggregatorFound", resourceCulture);
public static string UserAlreadyAdded => ResourceManager.GetString("UserAlreadyAdded", resourceCulture);
public static string NoUsersAdded => ResourceManager.GetString("NoUsersAdded", resourceCulture);
public static string AccessHelpText => ResourceManager.GetString("AccessHelpText", resourceCulture);
public static string SearchUsersPlaceholder => ResourceManager.GetString("SearchUsersPlaceholder", resourceCulture);
public static string RestrictAccess => ResourceManager.GetString("RestrictAccess", resourceCulture);
public static string AllowedUsers => ResourceManager.GetString("AllowedUsers", resourceCulture);
public static string Access => ResourceManager.GetString("Access", resourceCulture);
public static string Results => ResourceManager.GetString("Results", resourceCulture);
public static string PasswordRequirements => ResourceManager.GetString("PasswordRequirements", resourceCulture);
public static string InvalidEmailFormat => ResourceManager.GetString("InvalidEmailFormat", resourceCulture);
public static string UserNotFound => ResourceManager.GetString("UserNotFound", resourceCulture);
public static string TemplateNotFound => ResourceManager.GetString("TemplateNotFound", resourceCulture);
public static string SalesforceIntegrationError => ResourceManager.GetString("SalesforceIntegrationError", resourceCulture);
public static string AccountAndContactCreated => ResourceManager.GetString("AccountAndContactCreated", resourceCulture);
public static string SalesforceInvalidConfig => ResourceManager.GetString("SalesforceInvalidConfig", resourceCulture);
public static string SalesforceAuthError => ResourceManager.GetString("SalesforceAuthError", resourceCulture);
public static string SalesforceConnectionError => ResourceManager.GetString("SalesforceConnectionError", resourceCulture);
public static string SalesforceResponseError => ResourceManager.GetString("SalesforceResponseError", resourceCulture);
public static string SalesforceGeneralError => ResourceManager.GetString("SalesforceGeneralError", resourceCulture);
public static string SalesforceIntegrationTitle => ResourceManager.GetString("SalesforceIntegrationTitle", resourceCulture);
public static string SendToSalesforce => ResourceManager.GetString("SendToSalesforce", resourceCulture);
public static string AccountName => ResourceManager.GetString("AccountName", resourceCulture);
public static string ContactFirstName => ResourceManager.GetString("ContactFirstName", resourceCulture);
public static string ContactLastName => ResourceManager.GetString("ContactLastName", resourceCulture);
public static string ContactEmail => ResourceManager.GetString("ContactEmail", resourceCulture);
    }
} 