//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseProject.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedResources_es {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResources_es() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CourseProject.Resources.SharedResources.es", typeof(SharedResources_es).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acciones.
        /// </summary>
        internal static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Añadir.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar pregunta.
        /// </summary>
        internal static string AddQuestion {
            get {
                return ResourceManager.GetString("AddQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asignar como Administrador.
        /// </summary>
        internal static string AdminActionAssignAdmin {
            get {
                return ResourceManager.GetString("AdminActionAssignAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bloquear.
        /// </summary>
        internal static string AdminActionBlock {
            get {
                return ResourceManager.GetString("AdminActionBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar.
        /// </summary>
        internal static string AdminActionDelete {
            get {
                return ResourceManager.GetString("AdminActionDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar Rol de Administrador.
        /// </summary>
        internal static string AdminActionRemoveAdmin {
            get {
                return ResourceManager.GetString("AdminActionRemoveAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acciones.
        /// </summary>
        internal static string AdminActions {
            get {
                return ResourceManager.GetString("AdminActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desbloquear.
        /// </summary>
        internal static string AdminActionUnblock {
            get {
                return ResourceManager.GetString("AdminActionUnblock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, seleccione al menos un usuario..
        /// </summary>
        internal static string AdminErrorNoUsersSelected {
            get {
                return ResourceManager.GetString("AdminErrorNoUsersSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestión de usuarios.
        /// </summary>
        internal static string AdminPanelTitle {
            get {
                return ResourceManager.GetString("AdminPanelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrador.
        /// </summary>
        internal static string AdminRoleAdmin {
            get {
                return ResourceManager.GetString("AdminRoleAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario.
        /// </summary>
        internal static string AdminRoleUser {
            get {
                return ResourceManager.GetString("AdminRoleUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activo.
        /// </summary>
        internal static string AdminStatusActive {
            get {
                return ResourceManager.GetString("AdminStatusActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bloqueado.
        /// </summary>
        internal static string AdminStatusBlocked {
            get {
                return ResourceManager.GetString("AdminStatusBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo Electrónico.
        /// </summary>
        internal static string AdminTableEmail {
            get {
                return ResourceManager.GetString("AdminTableEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        internal static string AdminTableName {
            get {
                return ResourceManager.GetString("AdminTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rol.
        /// </summary>
        internal static string AdminTableRole {
            get {
                return ResourceManager.GetString("AdminTableRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        internal static string AdminTableStatus {
            get {
                return ResourceManager.GetString("AdminTableStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todas las plantillas.
        /// </summary>
        internal static string AllTemplates {
            get {
                return ResourceManager.GetString("AllTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respuestas.
        /// </summary>
        internal static string Answers {
            get {
                return ResourceManager.GetString("Answers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atrás.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examinar....
        /// </summary>
        internal static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Casilla de verificación.
        /// </summary>
        internal static string Checkbox {
            get {
                return ResourceManager.GetString("Checkbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estás seguro de que quieres eliminar esta pregunta?.
        /// </summary>
        internal static string ConfirmDeleteQuestion {
            get {
                return ResourceManager.GetString("ConfirmDeleteQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proyecto del curso.
        /// </summary>
        internal static string CP {
            get {
                return ResourceManager.GetString("CP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creado en.
        /// </summary>
        internal static string CreatedAt {
            get {
                return ResourceManager.GetString("CreatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Plantilla.
        /// </summary>
        internal static string CreateTemplate {
            get {
                return ResourceManager.GetString("CreateTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imagen actual.
        /// </summary>
        internal static string CurrentImage {
            get {
                return ResourceManager.GetString("CurrentImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oscuro.
        /// </summary>
        internal static string DarkTheme {
            get {
                return ResourceManager.GetString("DarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La descripción no puede exceder los 500 caracteres..
        /// </summary>
        internal static string DescriptionTooLong {
            get {
                return ResourceManager.GetString("DescriptionTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar pregunta.
        /// </summary>
        internal static string EditQuestion {
            get {
                return ResourceManager.GetString("EditQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pregunta de edición.
        /// </summary>
        internal static string EditQuestionPlaceholder {
            get {
                return ResourceManager.GetString("EditQuestionPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Plantilla.
        /// </summary>
        internal static string EditTemplate {
            get {
                return ResourceManager.GetString("EditTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Educación.
        /// </summary>
        internal static string Education {
            get {
                return ResourceManager.GetString("Education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al eliminar la pregunta.
        /// </summary>
        internal static string ErrorDeletingQuestion {
            get {
                return ResourceManager.GetString("ErrorDeletingQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acción inválida o ningún usuario seleccionado..
        /// </summary>
        internal static string ErrorInvalidAction {
            get {
                return ResourceManager.GetString("ErrorInvalidAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrada inválida..
        /// </summary>
        internal static string ErrorInvalidInput {
            get {
                return ResourceManager.GetString("ErrorInvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al iniciar sesión..
        /// </summary>
        internal static string ErrorLogin {
            get {
                return ResourceManager.GetString("ErrorLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se seleccionaron plantillas.
        /// </summary>
        internal static string ErrorNoTemplatesSelected {
            get {
                return ResourceManager.GetString("ErrorNoTemplatesSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al registrarse..
        /// </summary>
        internal static string ErrorRegister {
            get {
                return ResourceManager.GetString("ErrorRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al actualizar el orden de la pregunta..
        /// </summary>
        internal static string ErrorUpdatingQuestionOrder {
            get {
                return ResourceManager.GetString("ErrorUpdatingQuestionOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rellenar formulario.
        /// </summary>
        internal static string FillForm {
            get {
                return ResourceManager.GetString("FillForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formularios.
        /// </summary>
        internal static string Forms {
            get {
                return ResourceManager.GetString("Forms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hola.
        /// </summary>
        internal static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oculto en resultados.
        /// </summary>
        internal static string HiddenInResults {
            get {
                return ResourceManager.GetString("HiddenInResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imagen.
        /// </summary>
        internal static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La URL de la imagen no puede exceder los 500 caracteres..
        /// </summary>
        internal static string ImageUrlTooLong {
            get {
                return ResourceManager.GetString("ImageUrlTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número entero no negativo.
        /// </summary>
        internal static string Integer {
            get {
                return ResourceManager.GetString("Integer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inglés.
        /// </summary>
        internal static string LanguageEnglish {
            get {
                return ResourceManager.GetString("LanguageEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma.
        /// </summary>
        internal static string LanguageSelector {
            get {
                return ResourceManager.GetString("LanguageSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Español.
        /// </summary>
        internal static string LanguageSpanish {
            get {
                return ResourceManager.GetString("LanguageSpanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claro.
        /// </summary>
        internal static string LightTheme {
            get {
                return ResourceManager.GetString("LightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargando.
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar Sesión.
        /// </summary>
        internal static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo Electrónico.
        /// </summary>
        internal static string LoginEmail {
            get {
                return ResourceManager.GetString("LoginEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña.
        /// </summary>
        internal static string LoginPassword {
            get {
                return ResourceManager.GetString("LoginPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recordarme.
        /// </summary>
        internal static string LoginRememberMe {
            get {
                return ResourceManager.GetString("LoginRememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar Sesión.
        /// </summary>
        internal static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Máximo 4 preguntas de cada tipo permitidas..
        /// </summary>
        internal static string MaxQuestionsPerType {
            get {
                return ResourceManager.GetString("MaxQuestionsPerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre es obligatorio..
        /// </summary>
        internal static string NameRequired {
            get {
                return ResourceManager.GetString("NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre no puede exceder los 100 caracteres..
        /// </summary>
        internal static string NameTooLong {
            get {
                return ResourceManager.GetString("NameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panel de Administración.
        /// </summary>
        internal static string NavAdminPanel {
            get {
                return ResourceManager.GetString("NavAdminPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio.
        /// </summary>
        internal static string NavHome {
            get {
                return ResourceManager.GetString("NavHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar Sesión.
        /// </summary>
        internal static string NavLogin {
            get {
                return ResourceManager.GetString("NavLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar Sesión.
        /// </summary>
        internal static string NavLogout {
            get {
                return ResourceManager.GetString("NavLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrarse.
        /// </summary>
        internal static string NavRegister {
            get {
                return ResourceManager.GetString("NavRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ningún archivo seleccionado.
        /// </summary>
        internal static string NoFileChosen {
            get {
                return ResourceManager.GetString("NoFileChosen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontraron plantillas.
        /// </summary>
        internal static string NoResults {
            get {
                return ResourceManager.GetString("NoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otro.
        /// </summary>
        internal static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solo privadas.
        /// </summary>
        internal static string PrivateOnly {
            get {
                return ResourceManager.GetString("PrivateOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Público.
        /// </summary>
        internal static string Public {
            get {
                return ResourceManager.GetString("Public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solo públicas.
        /// </summary>
        internal static string PublicOnly {
            get {
                return ResourceManager.GetString("PublicOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publicar.
        /// </summary>
        internal static string Publish {
            get {
                return ResourceManager.GetString("Publish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pregunta no encontrada o acceso denegado..
        /// </summary>
        internal static string QuestionNotFoundOrAccessDenied {
            get {
                return ResourceManager.GetString("QuestionNotFoundOrAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preguntas.
        /// </summary>
        internal static string Questions {
            get {
                return ResourceManager.GetString("Questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de Preguntas.
        /// </summary>
        internal static string QuestionsList {
            get {
                return ResourceManager.GetString("QuestionsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuestionario.
        /// </summary>
        internal static string Quiz {
            get {
                return ResourceManager.GetString("Quiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrarse.
        /// </summary>
        internal static string RegisterButton {
            get {
                return ResourceManager.GetString("RegisterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo Electrónico.
        /// </summary>
        internal static string RegisterEmail {
            get {
                return ResourceManager.GetString("RegisterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        internal static string RegisterName {
            get {
                return ResourceManager.GetString("RegisterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña.
        /// </summary>
        internal static string RegisterPassword {
            get {
                return ResourceManager.GetString("RegisterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrarse.
        /// </summary>
        internal static string RegisterTitle {
            get {
                return ResourceManager.GetString("RegisterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resultados de búsqueda.
        /// </summary>
        internal static string SearchResults {
            get {
                return ResourceManager.GetString("SearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar tipo.
        /// </summary>
        internal static string SelectType {
            get {
                return ResourceManager.GetString("SelectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuración.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadena de una línea.
        /// </summary>
        internal static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar.
        /// </summary>
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acción {0} aplicada con éxito..
        /// </summary>
        internal static string SuccessActionApplied {
            get {
                return ResourceManager.GetString("SuccessActionApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plantillas seleccionadas eliminadas con éxito..
        /// </summary>
        internal static string SuccessDeleteTemplate {
            get {
                return ResourceManager.GetString("SuccessDeleteTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formulario enviado correctamente.
        /// </summary>
        internal static string SuccessFormSubmitted {
            get {
                return ResourceManager.GetString("SuccessFormSubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inició sesión con éxito..
        /// </summary>
        internal static string SuccessLogin {
            get {
                return ResourceManager.GetString("SuccessLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerró sesión con éxito..
        /// </summary>
        internal static string SuccessLogout {
            get {
                return ResourceManager.GetString("SuccessLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orden actualizado con éxito..
        /// </summary>
        internal static string SuccessOrderUpdated {
            get {
                return ResourceManager.GetString("SuccessOrderUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plantillas seleccionadas publicadas con éxito..
        /// </summary>
        internal static string SuccessPublishTemplate {
            get {
                return ResourceManager.GetString("SuccessPublishTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pregunta agregada con éxito..
        /// </summary>
        internal static string SuccessQuestionAdded {
            get {
                return ResourceManager.GetString("SuccessQuestionAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pregunta eliminada con éxito..
        /// </summary>
        internal static string SuccessQuestionDeleted {
            get {
                return ResourceManager.GetString("SuccessQuestionDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orden actualizado con éxito..
        /// </summary>
        internal static string SuccessQuestionUpdated {
            get {
                return ResourceManager.GetString("SuccessQuestionUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrado con éxito..
        /// </summary>
        internal static string SuccessRegister {
            get {
                return ResourceManager.GetString("SuccessRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plantilla creada con éxito..
        /// </summary>
        internal static string SuccessTemplateCreated {
            get {
                return ResourceManager.GetString("SuccessTemplateCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plantilla eliminada con éxito..
        /// </summary>
        internal static string SuccessTemplateDeleted {
            get {
                return ResourceManager.GetString("SuccessTemplateDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plantilla actualizada con éxito..
        /// </summary>
        internal static string SuccessTemplateUpdated {
            get {
                return ResourceManager.GetString("SuccessTemplateUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plantillas seleccionadas no publicadas con éxito..
        /// </summary>
        internal static string SuccessUnpublishTemplate {
            get {
                return ResourceManager.GetString("SuccessUnpublishTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etiquetas.
        /// </summary>
        internal static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ej., quiz, educación.
        /// </summary>
        internal static string TagsPlaceholder {
            get {
                return ResourceManager.GetString("TagsPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las etiquetas no pueden exceder los 500 caracteres..
        /// </summary>
        internal static string TagsTooLong {
            get {
                return ResourceManager.GetString("TagsTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plantilla no encontrada o acceso denegado..
        /// </summary>
        internal static string TemplateNotFoundOrAccessDenied {
            get {
                return ResourceManager.GetString("TemplateNotFoundOrAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mis Plantillas.
        /// </summary>
        internal static string TemplatesTitle {
            get {
                return ResourceManager.GetString("TemplatesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, corrija los errores de entrada..
        /// </summary>
        internal static string TErrorInvalidInput {
            get {
                return ResourceManager.GetString("TErrorInvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texto de varias líneas.
        /// </summary>
        internal static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tema.
        /// </summary>
        internal static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El tema no puede exceder los 50 caracteres..
        /// </summary>
        internal static string ThemeTooLong {
            get {
                return ResourceManager.GetString("ThemeTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Título.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anular publicación.
        /// </summary>
        internal static string Unpublish {
            get {
                return ResourceManager.GetString("Unpublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se requiere el ID de usuario..
        /// </summary>
        internal static string UserIdRequired {
            get {
                return ResourceManager.GetString("UserIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vista.
        /// </summary>
        internal static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver formulario.
        /// </summary>
        internal static string ViewForm {
            get {
                return ResourceManager.GetString("ViewForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver plantilla.
        /// </summary>
        internal static string ViewTemplate {
            get {
                return ResourceManager.GetString("ViewTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostrar en la tabla de resultados.
        /// </summary>
        internal static string VisibleInResults {
            get {
                return ResourceManager.GetString("VisibleInResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sí.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
